# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8da94100614f3f60af63dd5bf1315c4b9d5b2be05b44fd3ae14cfd4a7affbd3124e9cd32b3a561a3b66e4285a2ee3ba95b84747aa9784902089d74248bad2093

test:
  secret_key_base: 374e993b3855cbfa7c7e6205403b689bdb6d3d7b16c78909c199c38d4d17085afa0871d3c3c08c41618be23887004bffe28528fdce42a518d4792e7c993730dd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
